# Generated by Django 5.2.12 on 2026-04-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionlog',
            name='gaze_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionlog',
            name='head_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionlog',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionlog',
            name='roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionlog',
            name='yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionlog',
            name='yolo_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attentionlog',
            name='label',
            field=models.CharField(choices=[('Attentive', 'Attentive'), ('Partially Attentive', 'Partially Attentive'), ('Distracted', 'Distracted'), ('Distracted (Phone)', 'Distracted (Phone)'), ('Attentive (Reading)', 'Attentive (Reading)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attentionlog',
            name='object_detected',
            field=models.CharField(choices=[('none', 'None'), ('phone', 'Phone'), ('book', 'Book'), ('laptop', 'Laptop')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionsummary',
            name='phone_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessionsummary',
            name='reading_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sessionsummary',
            unique_together={('session', 'student')},
        ),
    ]
