# Generated by Django 6.0 on 2026-05-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attentionlog_gaze_score_attentionlog_head_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_summary', models.TextField()),
                ('peak_distraction_periods', models.JSONField(default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('avg_attention_score', models.FloatField()),
                ('total_students_tracked', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.session')),
            ],
        ),
    ]
